# Generated by Django 5.2.5 on 2025-10-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('jersey', 'Jersey'), ('accessories', 'Accessories'), ('keychain', 'Key Chain'), ('bag', 'Bag'), ('ball', 'Ball'), ('gloves', 'Gloves'), ('hat', 'Hat'), ('watch', 'Watch'), ('scarf', 'Scarf'), ('socks', 'Socks'), ('water_bottle', 'Water Bottle'), ('poster', 'Poster'), ('magazine', 'Magazine'), ('sticker', 'Sticker'), ('others', 'Others')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
